#!/usr/bin/env python3
"""Sync the federation contract artifact into this SDK's vendored copy (DEVX-S0, ADR-0001).

Source of truth:
    citrate-federation/contract/federation-contract.json
generated by:
    citrate-federation/scripts/gen-contract.mjs

    python scripts/sync_contract.py           # overwrite the vendored copy (verbatim)
    python scripts/sync_contract.py --check    # CI gate: non-zero if the vendored copy drifted

The copy is byte-verbatim so the drift check is exact across languages.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LABS_ROOT = REPO_ROOT.parent
CANONICAL = LABS_ROOT / "citrate-federation" / "contract" / "federation-contract.json"
VENDORED = REPO_ROOT / "citrate_sdk" / "_generated" / "federation_contract.json"


def main() -> int:
    check = "--check" in sys.argv[1:]
    if not CANONICAL.exists():
        print(
            f"[sync_contract] canonical not found at {CANONICAL}\n"
            "  Ensure citrate-federation is a sibling under citrate-labs/ and run\n"
            "  `node scripts/gen-contract.mjs` there first.",
            file=sys.stderr,
        )
        return 1

    raw = CANONICAL.read_text(encoding="utf-8")
    # Minimal shape gate so a malformed canonical cannot pollute the vendored copy.
    doc = json.loads(raw)
    if doc.get("schemaVersion") != 1:
        print(f"[sync_contract] unexpected schemaVersion {doc.get('schemaVersion')}", file=sys.stderr)
        return 1
    if doc.get("chain", {}).get("chainId") != 40204:
        print(f"[sync_contract] chainId {doc.get('chain', {}).get('chainId')}, expected 40204", file=sys.stderr)
        return 1

    if check:
        if not VENDORED.exists():
            print(f"[sync_contract] no vendored copy at {VENDORED}", file=sys.stderr)
            return 1
        if VENDORED.read_text(encoding="utf-8") != raw:
            print(
                "[sync_contract] vendored federation_contract.json is OUT OF SYNC. "
                "Run `python scripts/sync_contract.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print("[sync_contract] vendored contract matches canonical ✓")
        return 0

    VENDORED.parent.mkdir(parents=True, exist_ok=True)
    VENDORED.write_text(raw, encoding="utf-8")
    print(f"[sync_contract] wrote {VENDORED} (EntryPoint {doc['aaStack']['EntryPoint']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
