name: CI
on:
  push: { branches: [main] }
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python:
    uses: CitrateNetwork/.github/.github/workflows/reusable-python-ci.yml@main
